# --- Build stage ---
FROM golang:1.26.5 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o worker ./cmd/worker

# --- Runtime stage ---
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
poppler-utils \
ca-certificates \
&& rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app/worker .

CMD ["./worker"]